eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070
spring:
  application:
    name: school
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/school
    username: hussein
    password: tr6nsformers
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSqlDialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSqlDialect
#        format_sql: true
#    show-sql: true
application:
  config:
    #    students-url: http://localhost:8090/api/v1/students
    #with gateway port
    students-url: http://localhost:8222/api/v1/students
